### ISSUE TITLE
Pass in string to FKs and M2Ms instead of models

### ISSUE THREAD

**Issue by jlward** [derekjamerson/my_spotify_tool#11]
If you look at [this](https://github.com/derekjamerson/my_spotify_tool/blob/master/spotify_project/tracks/models.py#L11-L12), you'll see:

```python
    artists = models.ManyToManyField(Artist, related_name='tracks')
```

The first argument you have is the actual Model `Artist`. This is an old way of passing along this info. Now-a-days we pass in strings instead. It would look something like:

```python
    artists = models.ManyToManyField('artist.Artist', related_name='tracks')
```

Which follows the format of `{app_name}.{Model_name}`. All FKs, M2Ms, 1:1s, etc should be updated to use strings instead.

This change as made because Django care a lot about the order things are imported in. So, in `tracks` we are currently importing `Artist`. Which means, that the `Artist` model will get loaded in before the `Track` model does. In your case, I would be shocked if it actually mattered. But I've seen esoteric issues come up that are related to this.

**Comment by derekjamerson** [comment]
Oh, that makes sense. Thank you for the explanation.
