### ISSUE TITLE
Defining `objects` on models is only required if you are using a custom manager

### ISSUE THREAD

**Issue by jlward** [derekjamerson/my_spotify_tool#12]
In most of your models you have `objects = models.Manager()` If you are not using any custom managers then this should not be required. Django auto add this exact line behind the scenes.

**Comment by derekjamerson** [comment]
It's a PyCharm work-around to remove an error. It works without it, but it underlines it. I got annoyed and Googled it.

**Comment by jlward** [comment]
Lol, ok. There is probably some setting in PyCharm you can add to make it stop doing that, but I don't know what it would be. Feel free to close and ignore this one

**Comment by jlward** [comment]
https://www.jetbrains.com/help/pycharm/django-support7.html
